# ==========================
# PostgreSQL
# ==========================

spring.datasource.url=jdbc:postgresql://localhost:5432/urban_heat_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# ==========================
# Kafka
# ==========================

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=urban-heat-java
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

app.kafka.heat-topic=heat-measurements